CREATE TABLE vendor_info (
    id UUID PRIMARY KEY,
    vendor TEXT UNIQUE,
    s_and_c_cert JSONB,
    bus_type JSONB,
    data_collected JSONB,
    legal_compliance TEXT,
    published_subprocessors JSONB,
    privacy_policy_url TEXT,
    tos_url TEXT,
    date TEXT,
    logo TEXT,
    alias JSONB,
    data JSONB,
    security_rating DOUBLE PRECISION,
    risk_score INTEGER,
    risk_categories JSONB,
    compliance_certifications JSONB,
    headquarters_location TEXT,
    contact_email TEXT,
    breach_history JSONB,
    last_reviewed TIMESTAMP,
    website_url TEXT
);
